library(tidyverse)
library(DBI)
library(RMariaDB)
library(pool)

db_passwd <- rstudioapi::askForPassword("Database password")

con <- dbPool(drv=MariaDB(), host = "vm1788.kaj.pouta.csc.fi", dbname = "convoy", user = "convoy", password = db_passwd, bigint = "numeric", load_data_local_infile = T, validationInterval=10)
dbExecute(con, "SET SESSION storage_engine=aria")
coni <- dbPool(drv=MariaDB(), host = "vm1788.kaj.pouta.csc.fi", dbname = "convoy", user = "convoy", password = db_passwd, bigint = "integer64", load_data_local_infile = T, validationInterval=10)
dbExecute(coni, "SET SESSION storage_engine=aria")
rm(db_passwd)

tweets_c <- tbl(con,"tweets_c")
tweets_a <- tbl(con,"tweets_a")
tweet_stats_a <- tbl(con,"tweet_stats_a")
users_c <- tbl(con,"users_c")
users_a<- tbl(con,"users_a")
tweet_hashtags_c <- tbl(con,"tweet_hashtags_c")
tweet_hashtags_a <- tbl(con,"tweet_hashtags_a")
tweet_mentions_c <- tbl(con,"tweet_mentions_c")
tweet_mentions_a <- tbl(con,"tweet_mentions_a") 
tweet_urls_c <- tbl(con,"tweet_urls_c")
tweet_urls_a <- tbl(con,"tweet_urls_a") 
conversations_c <- tbl(con,"conversations_c")
conversations_a <- tbl(con,"conversations_a")
ur_conversations_c <- tbl(con,"ur_conversations_c")
ur_conversations_a <- tbl(con,"ur_conversations_a")

tweets_c_i <- tbl(coni,"tweets_c")
tweets_a_i <- tbl(coni,"tweets_a")
tweet_stats_a_i <- tbl(coni,"tweet_stats_a")
users_c_i <- tbl(coni,"users_c")
users_a_i <- tbl(coni,"users_a")
tweet_hashtags_c_i <- tbl(coni,"tweet_hashtags_c")
tweet_hashtags_a_i <- tbl(coni,"tweet_hashtags_a")
tweet_mentions_c_i <- tbl(coni,"tweet_mentions_c")
tweet_mentions_a_i <- tbl(coni,"tweet_mentions_a") 
tweet_urls_c_i <- tbl(coni,"tweet_urls_c")
tweet_urls_a_i <- tbl(coni,"tweet_urls_a") 
conversations_c_i <- tbl(coni,"conversations_c")
conversations_a_i <- tbl(coni,"conversations_a")
ur_conversations_c_i <- tbl(coni,"ur_conversations_c")
ur_conversations_a_i <- tbl(coni,"ur_conversations_a")

